# Generated by Django 3.1 on 2020-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CemanetEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200, null=True)),
                ('api_secret', models.CharField(max_length=200, null=True)),
                ('unique_ref', models.CharField(max_length=200, null=True)),
                ('clientId', models.CharField(max_length=200, null=True)),
                ('dlrEndpoint', models.CharField(max_length=200, null=True)),
                ('productId', models.CharField(max_length=200, null=True)),
                ('msisdn', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
