# Generated by Django 3.1 on 2020-09-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_cemanetendpoint_dlrendpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cemanetendpoint',
            name='clientId',
        ),
        migrations.RemoveField(
            model_name='cemanetendpoint',
            name='dlrEndpoint',
        ),
        migrations.RemoveField(
            model_name='cemanetendpoint',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='cemanetendpoint',
            name='unique_ref',
        ),
    ]
