# Generated by Django 3.1 on 2020-09-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_auto_20200902_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemanetendpoint',
            name='clientId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cemanetendpoint',
            name='dlrEndpoint',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cemanetendpoint',
            name='productId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cemanetendpoint',
            name='unique_ref',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
