# Generated by Django 3.1 on 2020-09-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_auto_20200902_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cemanetendpoint',
            old_name='api_key',
            new_name='my_api_key',
        ),
        migrations.RenameField(
            model_name='cemanetendpoint',
            old_name='api_secret',
            new_name='my_api_secret',
        ),
        migrations.RenameField(
            model_name='cemanetendpoint',
            old_name='clientId',
            new_name='my_clientId',
        ),
        migrations.RenameField(
            model_name='cemanetendpoint',
            old_name='dlrEndpoint',
            new_name='my_dlrEndpoint',
        ),
        migrations.RenameField(
            model_name='cemanetendpoint',
            old_name='message',
            new_name='my_message',
        ),
        migrations.RenameField(
            model_name='cemanetendpoint',
            old_name='msisdn',
            new_name='my_msisdn',
        ),
        migrations.RenameField(
            model_name='cemanetendpoint',
            old_name='productId',
            new_name='my_productId',
        ),
        migrations.RenameField(
            model_name='cemanetendpoint',
            old_name='unique_ref',
            new_name='my_unique_ref',
        ),
    ]
