# Generated by Django 3.1 on 2020-09-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_auto_20200904_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cemanetendpoint',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
